import { ArrowRight, BookOpenCheck, CircuitBoard, FileCheck2, LockKeyhole, ShieldCheck } from 'lucide-react';
import type { CatalogResponse } from '../types/api';

type Props = { catalog: CatalogResponse | null; onHome: () => void };

export function About({ catalog, onHome }: Props) {
  const models = catalog?.total_supported_models;
  return <div className="info-page">
    <section className="info-hero"><div><p className="eyebrow">About Ustad Assist</p><h1>A clearer path from equipment fault to safe action.</h1><p className="lede">Ustad Assist is a technical troubleshooting copilot for technicians working with supported solar inverters and UPS systems. It brings equipment identity, verified documentation, and safety-aware guidance into one focused workflow.</p></div><div className="info-hero-mark"><CircuitBoard size={32}/><span>Technical knowledge system</span></div></section>
    <section className="about-grid"><article className="info-panel"><p className="eyebrow">The problem</p><h2>Technical faults are time-sensitive and context-heavy.</h2><p>Technicians often work across different manufacturers, model families, alarm-code formats, and manual versions. Searching for the right answer under pressure can create unnecessary delay and unsafe assumptions.</p></article><article className="info-panel accent-panel"><p className="eyebrow">Our solution</p><h2>A disciplined interface for the right evidence.</h2><p>Ustad Assist narrows the search to supported equipment, accepts an exact model and issue code, then presents only the backend’s verified result with its source and safety treatment.</p></article></section>
    <section className="info-section"><div className="section-heading-row"><div><p className="eyebrow">How it works</p><h2>Identity → evidence → action</h2></div></div><div className="about-flow"><Flow icon={<CircuitBoard/>} index="01" title="Equipment" text="Select a supported equipment category."/><Flow icon={<LockKeyhole/>} index="02" title="Exact model" text="Choose manufacturer and exact model from the live catalog."/><Flow icon={<FileCheck2/>} index="03" title="Error / alarm" text="Submit the displayed code and observed symptom."/><Flow icon={<BookOpenCheck/>} index="04" title="Verified guidance" text="Review meaning, checks, source, and next action."/></div></section>
    <section className="about-grid"><article className="info-panel"><p className="eyebrow">Verified knowledge</p><h2>Sources are part of the result.</h2><p>Manufacturer manuals and verified technical documentation are treated as the source of truth. A citation is presented with the guidance so the technician can understand where the result came from.</p></article><article className="info-panel"><p className="eyebrow">AI assistance</p><h2>Assistance with boundaries.</h2><p>AI helps interpret the supported workflow and present grounded information. It does not invent troubleshooting facts, silently confirm an image candidate, or override the backend safety decision.</p></article></section>
    <section className="safety-band"><div className="safety-band-icon"><ShieldCheck size={23}/></div><div><p className="eyebrow">Safety by design</p><h2>When the system escalates, the interface makes that unmistakable.</h2><p>Safe user checks and technician-only checks remain clearly separated. If the authoritative safety signal requires escalation, the result treatment prioritizes caution over speed.</p></div></section>
    <section className="info-section supported-summary"><div><p className="eyebrow">Supported equipment</p><h2>Focused coverage, not invented coverage.</h2><p className="section-helper">The supported catalog is loaded from the backend at runtime{models ? ` and currently lists ${models} exact models` : ''}.</p></div><div className="supported-chips">{catalog?.categories.map((item) => <span key={item.equipment_category}>{item.equipment_category}</span>) ?? <span>Live catalog loading</span>}</div></section>
    <section className="closing-cta"><div><p className="eyebrow">The Ustad Assist principle</p><h2>Assist, don’t guess.</h2><p>Start with the equipment you are working on and let the evidence shape the next action.</p></div><button className="button button-primary" onClick={onHome}>Explore supported equipment <ArrowRight size={16}/></button></section>
  </div>;
}

function Flow({ icon, index, title, text }: { icon: React.ReactNode; index: string; title: string; text: string }) { return <div className="flow-card"><span className="flow-icon">{icon}</span><span className="flow-index mono">{index}</span><h3>{title}</h3><p>{text}</p></div>; }
